import { z } from 'zod';
import { useSafeValidatedBody } from 'h3-zod';
import PassageModel from '../../models/Passage';
import ApparatusModel from '../../models/Apparatus';

const FINAL_TYPE_CONFIG = {
  WITH_HAND: {
    label: 'gymnastique avec engin à main',
    targetApparatusCode: 'GYAE',
    sourceApparatusCodes: ['avec-engin-12x12', 'avec-engin-12x14', 'avec-engin-12x18']
  },
  WITHOUT_HAND: {
    label: 'gymnastique sans engin à main',
    targetApparatusCode: 'GYSE',
    sourceApparatusCodes: ['sans-engin-12x12', 'sans-engin-12x14', 'sans-engin-12x18']
  }
} as const;

type FinalType = keyof typeof FINAL_TYPE_CONFIG;

const ZURICH_SATURDAY = 'sat';

const isSaturdayInZurich = (date: Date) => {
  const weekday = new Intl.DateTimeFormat('en-GB', {
    timeZone: 'Europe/Zurich',
    weekday: 'short'
  })
    .format(date)
    .toLowerCase();
  return weekday.startsWith(ZURICH_SATURDAY);
};

/**
 * Zod schema for finals generation request.
 */
const schema = z.object({
  finalType: z.enum(['WITH_HAND', 'WITHOUT_HAND']).describe('Final discipline to generate'),
  qualifiersCount: z.number().min(1).max(20).default(3).describe('Number of top groups to qualify'),
  startTime: z.string().describe('ISO string or parseable date string for the first final passage'),
  intervalMinutes: z.number().min(1).max(30).default(8).describe('Gap between each final passage'),
  location: z.string().optional().describe('Location where finals take place'),
  customOrderGroupIds: z.array(z.string()).optional().describe('Custom passage order for qualified groups'),
  replaceExisting: z.boolean().default(false).describe('Replace existing finals for this final type')
});

/**
 * Admin endpoint to generate final round passages based on qualifier results.
 * Finals are generated by discipline family:
 * - WITH_HAND: merges all "avec-engin-*" qualifier surfaces into one final (GYAE)
 * - WITHOUT_HAND: merges all "sans-engin-*" qualifier surfaces into one final (GYSE)
 */
export default defineEventHandler(async (event) => {
  const result = await useSafeValidatedBody(event, schema);
  if (!result.success) {
    throw createError({ statusCode: 400, statusMessage: 'Invalid parameters', data: result.error });
  }
  
  const { 
    finalType,
    qualifiersCount, 
    startTime, 
    intervalMinutes, 
    location,
    customOrderGroupIds = [],
    replaceExisting
  } = result.data;

  try {
    const parsedStartTime = new Date(startTime);
    if (Number.isNaN(parsedStartTime.getTime())) {
      throw createError({ statusCode: 400, statusMessage: 'Heure de début invalide.' });
    }

    if (!isSaturdayInZurich(parsedStartTime)) {
      throw createError({
        statusCode: 400,
        statusMessage: 'Les finales doivent être programmées le samedi (heure Europe/Zurich).'
      });
    }

    const config = FINAL_TYPE_CONFIG[finalType as FinalType];
    if (!config) {
      throw createError({ statusCode: 400, statusMessage: 'Type de finale invalide.' });
    }

    const [targetApparatus, sourceApparatuses] = await Promise.all([
      ApparatusModel.findOne({ code: config.targetApparatusCode }),
      ApparatusModel.find({ code: { $in: config.sourceApparatusCodes } }).select('_id code')
    ]);

    if (!targetApparatus) {
      throw createError({
        statusCode: 404,
        statusMessage: `Engin de finale introuvable (${config.targetApparatusCode}).`
      });
    }

    if (sourceApparatuses.length !== config.sourceApparatusCodes.length) {
      throw createError({
        statusCode: 400,
        statusMessage: 'Impossible de retrouver toutes les surfaces de qualification nécessaires.'
      });
    }

    const existingFinalsCount = await PassageModel.countDocuments({
      apparatus: targetApparatus._id,
      round: 'FINAL'
    });

    if (existingFinalsCount > 0 && !replaceExisting) {
      throw createError({
        statusCode: 400,
        statusMessage: `Les finales ${config.label} existent déjà. Activez le remplacement pour les regénérer.`
      });
    }

    const sourceApparatusIds = sourceApparatuses.map((a) => a._id);
    const qualifiers = await PassageModel.aggregate([
      {
        $match: {
          apparatus: { $in: sourceApparatusIds },
          round: 'QUALIFIER',
          isPublished: true,
          score: { $ne: null }
        }
      },
      {
        $lookup: {
          from: 'groups',
          localField: 'group',
          foreignField: '_id',
          as: 'groupInfo'
        }
      },
      { $unwind: '$groupInfo' },
      { $sort: { score: -1, startTime: 1 } },
      {
        $group: {
          _id: '$group',
          group: { $first: '$group' },
          groupName: { $first: '$groupInfo.name' },
          score: { $first: '$score' },
          location: { $first: '$location' }
        }
      },
      { $sort: { score: -1 } },
      { $limit: qualifiersCount }
    ]);

    if (qualifiers.length === 0) {
      return {
        success: false,
        message: `Aucune note de qualification publiée trouvée pour ${config.label}.`
      };
    }

    const defaultOrder = [...qualifiers].reverse();
    let orderedQualifiers = defaultOrder;

    if (customOrderGroupIds.length > 0) {
      const normalizedCustomOrder = customOrderGroupIds.map((id) => String(id));
      const uniqueCustomOrder = new Set(normalizedCustomOrder);
      const defaultIds = defaultOrder.map((q: any) => String(q.group));
      const defaultIdSet = new Set(defaultIds);

      if (uniqueCustomOrder.size !== normalizedCustomOrder.length) {
        throw createError({
          statusCode: 400,
          statusMessage: 'L’ordre personnalisé contient des doublons.'
        });
      }

      if (normalizedCustomOrder.length !== defaultOrder.length) {
        throw createError({
          statusCode: 400,
          statusMessage: 'L’ordre personnalisé doit contenir exactement tous les finalistes sélectionnés.'
        });
      }

      const hasUnknownGroup = normalizedCustomOrder.some((id) => !defaultIdSet.has(id));
      if (hasUnknownGroup) {
        throw createError({
          statusCode: 400,
          statusMessage: 'L’ordre personnalisé contient un groupe non qualifié.'
        });
      }

      const defaultByGroup = new Map(defaultOrder.map((q: any) => [String(q.group), q]));
      orderedQualifiers = normalizedCustomOrder.map((id) => defaultByGroup.get(id)!);
    }

    if (replaceExisting && existingFinalsCount > 0) {
      await PassageModel.deleteMany({
        apparatus: targetApparatus._id,
        round: 'FINAL'
      });
    }

    const finalPassages = [];
    let currentStartTime = new Date(parsedStartTime);

    for (const q of orderedQualifiers) {
      const endTime = new Date(currentStartTime.getTime() + intervalMinutes * 60000);
      
      finalPassages.push({
        group: q.group,
        apparatus: targetApparatus._id,
        startTime: new Date(currentStartTime),
        endTime: new Date(endTime),
        location: location || q.location,
        round: 'FINAL',
        status: 'SCHEDULED',
        score: null,
        isPublished: false
      });

      currentStartTime = new Date(endTime.getTime());
    }

    const inserted = await PassageModel.insertMany(finalPassages);

    try {
      const cacheStorage = useStorage('cache')
      const allCacheKeys = await cacheStorage.getKeys()
      if (allCacheKeys.length > 0) {
        await Promise.all(allCacheKeys.map(key => cacheStorage.removeItem(key)))
        console.log(`[admin:finals] Cleared ${allCacheKeys.length} Nitro cache entries`)
      }
    } catch (cacheErr) {
      console.warn('[admin:finals] Could not clear Nitro cache:', cacheErr)
    }

    return {
      success: true,
      message: `${inserted.length} passages de finale ${config.label} générés.`,
      data: inserted
    };

  } catch (error: any) {
    console.error('[admin:finals] Generation failed:', error);
    throw createError({
      statusCode: error.statusCode || 500,
      statusMessage: error.statusMessage || 'Internal Server Error'
    });
  }
});
